server:
  port: 8080
spring:
  application:
    name: book-service
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/book-service-db
    username: amigoscode
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true